### ISSUE TITLE
Owncloud plugin on Ubuntu 12.04 - hangs on save function

### ISSUE THREAD

**Issue by afiore1961** [lebowski42/dokuwiki-owncloud#1]
Running Ubuntu 12.04 I was able to set up on my hosting account with Bluehost.com.
However when I make a changean and try to save it hangs permanently.

Which Pear php packages are required by this plugin? 
Thanks

**Comment by lebowski42** [comment]
Di you solve this issue? There is no special pear package requiered.

**Comment by afiore1961** [comment]
No -  My tech support in two hosting sites made some adjustments - mainly adjusting the  path to their pear and php packages. The result: having owncloud plugin enabled,  does not prevent access to my dokuwiki wikis - but any attempt to load new media triggers the same problems. Thus I keep the owncloud plug-in disabled.
if you have found a solution let me know

**Comment by Kungi** [comment]
I have the same problem here on debian wheezy.

When the plugin is enabled every save operation leads to a blank page and the edit is not saved.
When I disable the plugin and make the edit and then reenable it everything looks fine till the next
edit.

I am running the latest version of the plugin on nginx 1.2.1 with dokuwiki rc2013-10-28 "Binky"

I also tried the plugin with the latest stable release 2013-05-10a "Weatherwax" and I have the same problem. After saving a page containing for example {{:wiki?fileid=94|wiki}} the browser displays a blank
page. Although the preview is working fine.

**Comment by Poukram35** [comment]
Hi,
I've just done the same tests than Kungi and have exactly the same issue.

I'm on Ubuntu 12.04
I installed owncloud which works fine alone
I installed Dokuwiki rc2013-10-28 "Binky" which works fine alone
I installed owncloud plugin for dokuwiki and then i have the issue of save operation : blank page and edit is not saved (note : only when a document is linked in the page !  When there is only text, save operation works)
So tried with Dokuwiki Weatherwax and I also have the same problem.

No message in any logs...

Any solution ?

PS : an other issue but with authownCloud Plugin -> the shared user backend doesn't seem to work...

**Comment by Kungi** [comment]
Regarding your PS: the authownplugin plugin does not work on my server either.

**Comment by Poukram35** [comment]
My colleague save me ! ;-)

Actually my owncloud is installed with SQLitebecause it's just for test. In the plugin in action.php, the following resquest is done :

$helper->dbQuery('INSERT IGNORE INTO `*PREFIX*dokuwiki_media_use` (`fileid`, `wikipage`,`wikipage_hash`,`firstheading`) VALUES (?,?,?,?)', array($fileid, $ID, md5($ID), $heading));
    } 

But SQLite doesn't use "INSERT IGNORE", only "INSERT OR IGNORE" 

My colleague suggest the following fix for helper.php :

Line 61 replace "public function dbQuery($sql, $params)" by the following

```
public function dbQuery($sql, $params){
    $dbtype = OC_Config::getValue('dbtype', 'sqlite');
    if($dbtype == 'sqlite' || $dbtype == 'sqlite3') $sql = str_replace('INSERT IGNORE', 'INSERT OR IGNORE', $sql);
    $db = OC_DB::prepare($sql);
    $this->lastQuery = $db->execute($params);
}
```

And now it works ! 
Hope this is the same solution for all of you... :-)

**Comment by lebowski42** [comment]
For problems with the 'shared user backend' see here: https://github.com/lebowski42/dokuwiki-authowncloud

**Comment by Kungi** [comment]
Thank you so much. It works now.
