### ISSUE TITLE
function declared in dokuwiki and in owncloud colliding

### ISSUE THREAD

**Issue by bjuergens** [lebowski42/dokuwiki-owncloud#14]
I installed the owncloud-plugin for dokuwiki and the dokuwikiplugin for owncloud. 
Then I made the first article, that included `{{favorites:image.png |My favorite image}}'. Then the entire dokwiki was broken and it only served blank pages from there on. 

the apache-log says: (/var/log/apache2/error.log)

```
[Sun Aug 23 12:54:25.106063 2015] [:error] [pid 9883] [client 217.231.109.161:40970] PHP Fatal error:  Cannot redeclare script() (previously declared in /var/www/dokuwiki/inc/common.php:625) in /var/www/owncloud/lib/private/template/functions.php on line 54
```

to get my dokowiki working again I did this:
1. rename plugin: `cd var/www/dokuwiki/lib/plugins && sudo mv owncloud/ owncloud_bak/`
2. go into dokuwiki's admin panel and remove it there. 

Versions:
- ownCloud 8.1.1 (stable) 
- DokuWiki version: Release 2015-08-10 "Detritus"

**Comment by wotanii** [comment]
Versions:
- DokuWiki version: Release 2015-08-10 "Detritus"
- ownCloud 8.1.1 (stable)
